version: "3.9"

services:
  api:
    build:
      context: ""
      dockerfile: Dockerfile.dev
    image: "localhost:7002/photo-backend-dev:${IMAGE_TAG}"
    container_name: "${CONT_NAME}"
    ports:
      - "${PORT}:7159"